<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/selectize.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/parsley/dist/parsley.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/jquery.placeholder.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/jQuery.equalHeights.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/icheck.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/jquery.vanillabox-0.1.5.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/countdown.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/retina-1.1.0.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/custom.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/alumni/js/bootstrap-datepicker.js"></script>
